site_name: Porism
site_author: Jeremy Ong

theme: cinder

nav:
  - 'Home': 'index.md'
  - 'About': 'about.md'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML

copyright: 'Jeremy Ong 2019'

markdown_extensions:
  - mdx_math